# reports:
#   exclude_paths:
#     - contracts/*.*

hypothesis:
  max_examples: 1
  phases:
    explicit: true
    reuse: true
    generate: true
    target: true
    shrink: true

autofetch_sources: true