project_structure:
  build: build
  contracts: contracts
  interfaces: interfaces
  reports: reports
  scripts: scripts
  tests: tests

reports:
  exclude_paths: 
    - interfaces/*.*
    - contracts/testing/*.*

hypothesis:
  max_examples: 1
  phases:
    explicit: true
    reuse: true
    generate: true
    target: true
    shrink: true

networks:
  development:
    cmd_settings:
      accounts: 20

autofetch_sources: true

dependencies:
  - curvefi/curve-contract@1.0
  - curvefi/curve-dao-contracts@1.1.0
  - Uniswap/uniswap-v2-core@1.0.1
